### ISSUE TITLE
Incorrect return value for EstimateFalsePositiveRate

### ISSUE THREAD

**Issue by ErikDubbelboer** [willf/bloom#20]
At [line 77](https://github.com/willf/bloom/blob/master/bloom.go#L177) [EstimateFalsePositiveRate](https://github.com/willf/bloom/blob/master/bloom.go#L161) returns the number of false positives found divided by 100. This makes no sense as the number of tests performed depends on the input number. Choosing a higher `n` will now increase the number of false positives by a too high amount.

The correct return value would be the number of false positives found depending on the number of tests performed:
```go
fp_rate = float64(fp) / float64(rounds) * float64(100)
```

**Comment by willf** [comment]
Fixed in d9cd4ac
