### ISSUE TITLE
Incorrect tests

### ISSUE THREAD

**Issue by ErikDubbelboer** [willf/bloom#21]
Some of the tests are faulty. [TestDirect20_5](https://github.com/willf/bloom/blob/master/bloom_test.go#L117) for example. If we use the formula from [estimateParameters](https://github.com/willf/bloom/blob/master/bloom.go#L95) (which is the same as the formula on [wikipedia](http://en.wikipedia.org/wiki/Bloom_filter#Probability_of_false_positives)). We get that for 10000 entries and a 0.0001% precision (p = 0.000001 because `EstimateFalsePositiveRate` (after fix #20) returns a 100-0 range and `estimateParameters` uses a 1-0 range) the hash should have 287,552 bits and 20 hashing functions. The values used in the test (200,000 bits and only 5 hashing functions) there for result in a much higher false positive chance of 0.03%.

Even with the #20 fix the tests still pass but this is only because the Fnv hashing functions used results in a really weird false positive rate for different inputs. Some inputs result in a much lower false positive rate (which I still don't understand) and many other result in a much higher false positive rate than expected.

For testing I quickly hacked a version which uses the Sha256 hashing function and the research from [Less Hashing, Same Performance: Building a Better Bloom Filter](http://www.eecs.harvard.edu/~kirsch/pubs/bbbf/esa06.pdf) (also used in [my redis bloom filter](https://github.com/ErikDubbelboer/redis-lua-scaling-bloom-filter/blob/master/add.lua#L27)). This version always results in the correct false positive rate but is around 26 times slower. If you are interested I can make a fork with this code so you can see if it's interesting.

**Comment by willf** [comment]
Thanks for pointing this out. I’ll review and get to it as soon as I can. 

-- 
Will


On March 13, 2015 at 4:21:59 AM, Erik Dubbelboer (notifications@github.com) wrote:

Some of the tests are faulty. TestDirect20_5 for example. If we use the formula from estimateParameters (which is the same as the formula on wikipedia). We get that for 10000 entries and a 0.0001% precision (p = 0.000001 because EstimateFalsePositiveRate (after fix #20) returns a 100-0 range and estimateParameters uses a 1-0 range) the hash should have 287,552 bits and 20 hashing functions. The values used in the test (200,000 bits and only 5 hashing functions) there for result in a much higher false positive chance of 0.03%.

Even with the #20 fix the tests still pass but this is only because the Fnv hashing functions used results in a really weird false positive rate for different inputs. Some inputs result in a much lower false positive rate (which I still don't understand) and many other result in a much higher false positive rate than expected.

For testing I quickly hacked a version which uses the Sha256 hashing function and the research from Less Hashing, Same Performance: Building a Better Bloom Filter (also used in my redis bloom filter). This version always results in the correct false positive rate but is around 26 times slower. If you are interested I can make a fork with this code so you can see if it's interesting.

**Comment by willf** [comment]
Erik, I've reviewed the tests, and I think they are ok. The TestDirect* tests are not particularly useful ones since the number of bits used is 15 or 20 times the number needed. These were just tests written along the way; I don't think they particularly add anything.

Do you see a problem with the TestEstimated* tests?

**Comment by willf** [comment]
Erik, feel free to reopen if you disagree.

**Comment by ErikDubbelboer** [comment]
It still seems like the hash function is still quite bad and results in a much higher false positive rate than expected.

I fixed a version that uses a sha256 hash instead: https://github.com/ErikDubbelboer/bloom/commit/f822b4c907f14d93317d9e999dfea3f0d9abe34f

Below is the output of a small program to show some false positive rates for different estimates and sizes. As you can see the sha256 version false positive rates are much more around the estimated values. The fnvhash version is in my opinion much to inaccurate.

```
fnv NewWithEstimates(     1000,  0.1%).EstimateFalsePositiveRate(     1000) =  0.0%
fnv NewWithEstimates(    10000,  0.1%).EstimateFalsePositiveRate(    10000) =  0.0%
fnv NewWithEstimates( 10000000,  0.1%).EstimateFalsePositiveRate( 10000000) = 50.0%
fnv NewWithEstimates(100000000,  0.1%).EstimateFalsePositiveRate(100000000) =  1.5%
fnv NewWithEstimates(     1000,  1.0%).EstimateFalsePositiveRate(     1000) = 23.8%
fnv NewWithEstimates(    10000,  1.0%).EstimateFalsePositiveRate(    10000) =  0.1%
fnv NewWithEstimates( 10000000,  1.0%).EstimateFalsePositiveRate( 10000000) = 28.8%
fnv NewWithEstimates(100000000,  1.0%).EstimateFalsePositiveRate(100000000) = 17.1%
fnv NewWithEstimates(     1000,  2.0%).EstimateFalsePositiveRate(     1000) = 13.4%
fnv NewWithEstimates(    10000,  2.0%).EstimateFalsePositiveRate(    10000) =  1.4%
fnv NewWithEstimates( 10000000,  2.0%).EstimateFalsePositiveRate( 10000000) = 51.6%
fnv NewWithEstimates(100000000,  2.0%).EstimateFalsePositiveRate(100000000) = 17.1%
fnv NewWithEstimates(     1000, 10.0%).EstimateFalsePositiveRate(     1000) = 37.6%
fnv NewWithEstimates(    10000, 10.0%).EstimateFalsePositiveRate(    10000) =  5.0%
fnv NewWithEstimates( 10000000, 10.0%).EstimateFalsePositiveRate( 10000000) = 54.3%
fnv NewWithEstimates(100000000, 10.0%).EstimateFalsePositiveRate(100000000) = 17.2%

sha NewWithEstimates(     1000,  0.1%).EstimateFalsePositiveRate(     1000) =  0.2%
sha NewWithEstimates(    10000,  0.1%).EstimateFalsePositiveRate(    10000) =  0.1%
sha NewWithEstimates( 10000000,  0.1%).EstimateFalsePositiveRate( 10000000) =  0.1%
sha NewWithEstimates(100000000,  0.1%).EstimateFalsePositiveRate(100000000) =  0.1%
sha NewWithEstimates(     1000,  1.0%).EstimateFalsePositiveRate(     1000) =  1.2%
sha NewWithEstimates(    10000,  1.0%).EstimateFalsePositiveRate(    10000) =  1.0%
sha NewWithEstimates( 10000000,  1.0%).EstimateFalsePositiveRate( 10000000) =  1.0%
sha NewWithEstimates(100000000,  1.0%).EstimateFalsePositiveRate(100000000) =  1.0%
sha NewWithEstimates(     1000,  2.0%).EstimateFalsePositiveRate(     1000) =  2.1%
sha NewWithEstimates(    10000,  2.0%).EstimateFalsePositiveRate(    10000) =  2.0%
sha NewWithEstimates( 10000000,  2.0%).EstimateFalsePositiveRate( 10000000) =  2.0%
sha NewWithEstimates(100000000,  2.0%).EstimateFalsePositiveRate(100000000) =  2.0%
sha NewWithEstimates(     1000, 10.0%).EstimateFalsePositiveRate(     1000) =  9.7%
sha NewWithEstimates(    10000, 10.0%).EstimateFalsePositiveRate(    10000) =  9.8%
sha NewWithEstimates( 10000000, 10.0%).EstimateFalsePositiveRate( 10000000) = 10.3%
sha NewWithEstimates(100000000, 10.0%).EstimateFalsePositiveRate(100000000) = 10.3%
```

```go
package main

import (
  "fmt"
  "math/rand"
  "runtime"

  b2 "github.com/erikdubbelboer/bloom"
  b1 "github.com/willf/bloom"
)

func main() {
  rand.Seed(0)

  for _, f := range []float64{0.001, 0.01, 0.02, 0.1} {
    for _, n := range []uint{1000, 10000, 10000000, 100000000} {
      runtime.GC()
      fmt.Printf("fnv NewWithEstimates(%9d, %4.1f%%).EstimateFalsePositiveRate(%9d) = %4.1f%%\n", n, f*100, n, b1.NewWithEstimates(n, f).EstimateFalsePositiveRate(n))
    }
  }

  fmt.Printf("\n")

  for _, f := range []float64{0.001, 0.01, 0.02, 0.1} {
    for _, n := range []uint{1000, 10000, 10000000, 100000000} {
      runtime.GC()
      fmt.Printf("sha NewWithEstimates(%9d, %4.1f%%).EstimateFalsePositiveRate(%9d) = %4.1f%%\n", n, f*100, n, b2.NewWithEstimates(n, f).EstimateFalsePositiveRate(n))
    }
  }
}
```

**Comment by willf** [comment]
Erik, thanks for continuing to push for this.

**Comment by willf** [comment]
Oddly, I get exactly the same bad results, when I run the tests, but  on the _SHA_ code:

```
sha NewWithEstimates(     1000,  0.1%).EstimateFalsePositiveRate(     1000) =  0.0%
sha NewWithEstimates(    10000,  0.1%).EstimateFalsePositiveRate(    10000) =  0.0%
sha NewWithEstimates( 10000000,  0.1%).EstimateFalsePositiveRate( 10000000) = 50.0%
sha NewWithEstimates(100000000,  0.1%).EstimateFalsePositiveRate(100000000) =  1.5%
sha NewWithEstimates(     1000,  1.0%).EstimateFalsePositiveRate(     1000) = 23.8%
sha NewWithEstimates(    10000,  1.0%).EstimateFalsePositiveRate(    10000) =  0.1%
sha NewWithEstimates( 10000000,  1.0%).EstimateFalsePositiveRate( 10000000) = 28.8%
sha NewWithEstimates(100000000,  1.0%).EstimateFalsePositiveRate(100000000) = 17.1%
sha NewWithEstimates(     1000,  2.0%).EstimateFalsePositiveRate(     1000) = 13.4%
sha NewWithEstimates(    10000,  2.0%).EstimateFalsePositiveRate(    10000) =  1.4%
sha NewWithEstimates( 10000000,  2.0%).EstimateFalsePositiveRate( 10000000) = 51.6%
sha NewWithEstimates(100000000,  2.0%).EstimateFalsePositiveRate(100000000) = 17.1%
sha NewWithEstimates(     1000, 10.0%).EstimateFalsePositiveRate(     1000) = 37.6%
sha NewWithEstimates(    10000, 10.0%).EstimateFalsePositiveRate(    10000) =  5.0%
sha NewWithEstimates( 10000000, 10.0%).EstimateFalsePositiveRate( 10000000) = 54.3%
sha NewWithEstimates(100000000, 10.0%).EstimateFalsePositiveRate(100000000) = 17.2%
```

Investigating...

**Comment by ErikDubbelboer** [comment]
If you use the program above to test you need to checkout the [sha256](https://github.com/erikdubbelboer/bloom/tree/sha256) branch in my version. The master branch doesn't contain any changes.

**Comment by willf** [comment]
Ok, it looks like it was a bug in the the EstimateFalsePositiveRate function. It's using fnv again (and is back to creating hashes based on two fnv calls.

**Comment by ErikDubbelboer** [comment]
The two base hash works much better than I expected for such a fast hash function. These are the new results (with my fix to `EstimateFalsePositiveRate` below):
```
fnv NewWithEstimates(     1000,  0.1%).EstimateFalsePositiveRate(     1000) =  0.2%
fnv NewWithEstimates(    10000,  0.1%).EstimateFalsePositiveRate(    10000) =  0.5%
fnv NewWithEstimates( 10000000,  0.1%).EstimateFalsePositiveRate( 10000000) =  0.5%
fnv NewWithEstimates(100000000,  0.1%).EstimateFalsePositiveRate(100000000) =  0.0%
fnv NewWithEstimates(     1000,  1.0%).EstimateFalsePositiveRate(     1000) =  1.0%
fnv NewWithEstimates(    10000,  1.0%).EstimateFalsePositiveRate(    10000) =  0.5%
fnv NewWithEstimates( 10000000,  1.0%).EstimateFalsePositiveRate( 10000000) =  1.1%
fnv NewWithEstimates(100000000,  1.0%).EstimateFalsePositiveRate(100000000) =  1.1%
fnv NewWithEstimates(     1000,  2.0%).EstimateFalsePositiveRate(     1000) =  0.8%
fnv NewWithEstimates(    10000,  2.0%).EstimateFalsePositiveRate(    10000) =  2.9%
fnv NewWithEstimates( 10000000,  2.0%).EstimateFalsePositiveRate( 10000000) =  0.9%
fnv NewWithEstimates(100000000,  2.0%).EstimateFalsePositiveRate(100000000) =  4.6%
fnv NewWithEstimates(     1000, 10.0%).EstimateFalsePositiveRate(     1000) =  3.9%
fnv NewWithEstimates(    10000, 10.0%).EstimateFalsePositiveRate(    10000) =  6.3%
fnv NewWithEstimates( 10000000, 10.0%).EstimateFalsePositiveRate( 10000000) = 11.4%
fnv NewWithEstimates(100000000, 10.0%).EstimateFalsePositiveRate(100000000) =  5.7%
```

However I don't think the change you made to EstimateFalsePositiveRate is correct. Maybe I'm misunderstanding what you want the function to return so correct me if I'm wrong.

Your current code is:
```go
fpRate = float64(fp) / (float64(rounds) * float64(100))
```
This means that if we do 100 tests (`rounds = 100`) of which 20 are false (`fp = 20`) , we get an `fpRate = 20 / (100 * 100) = 0.002` which makes no sense to me. Similar to the input of `NewWithEstimates` I expect the function to return a percentage in the range of 1 to 0 where 1 equals 100%. At the moment it returns the percentage in the range of 0.01 to 0 where 0.01 equals 100%.

I think the correct code should just be:
```go
fpRate = float64(fp) / float64(rounds)
```
In the same case as above it would be `fpRate = 20 / 100 = 0.2`. This way `bloom.NewWithEstimates(n, f).EstimateFalsePositiveRate(n) == f` should in theory be true (not in practice of course).

Keep in mind that if you change this the TestEstimated* tests will fail again.

**Comment by willf** [comment]
Argh, you are right of course.

-- 
Will


On March 30, 2015 at 1:43:38 AM, Erik Dubbelboer (notifications@github.com) wrote:

The two base hash works much better than I expected for such a fast hash function. These are the new results (with my fix to EstimateFalsePositiveRate below):

fnv NewWithEstimates(     1000,  0.1%).EstimateFalsePositiveRate(     1000) =  0.2%
fnv NewWithEstimates(    10000,  0.1%).EstimateFalsePositiveRate(    10000) =  0.5%
fnv NewWithEstimates( 10000000,  0.1%).EstimateFalsePositiveRate( 10000000) =  0.5%
fnv NewWithEstimates(100000000,  0.1%).EstimateFalsePositiveRate(100000000) =  0.0%
fnv NewWithEstimates(     1000,  1.0%).EstimateFalsePositiveRate(     1000) =  1.0%
fnv NewWithEstimates(    10000,  1.0%).EstimateFalsePositiveRate(    10000) =  0.5%
fnv NewWithEstimates( 10000000,  1.0%).EstimateFalsePositiveRate( 10000000) =  1.1%
fnv NewWithEstimates(100000000,  1.0%).EstimateFalsePositiveRate(100000000) =  1.1%
fnv NewWithEstimates(     1000,  2.0%).EstimateFalsePositiveRate(     1000) =  0.8%
fnv NewWithEstimates(    10000,  2.0%).EstimateFalsePositiveRate(    10000) =  2.9%
fnv NewWithEstimates( 10000000,  2.0%).EstimateFalsePositiveRate( 10000000) =  0.9%
fnv NewWithEstimates(100000000,  2.0%).EstimateFalsePositiveRate(100000000) =  4.6%
fnv NewWithEstimates(     1000, 10.0%).EstimateFalsePositiveRate(     1000) =  3.9%
fnv NewWithEstimates(    10000, 10.0%).EstimateFalsePositiveRate(    10000) =  6.3%
fnv NewWithEstimates( 10000000, 10.0%).EstimateFalsePositiveRate( 10000000) = 11.4%
fnv NewWithEstimates(100000000, 10.0%).EstimateFalsePositiveRate(100000000) =  5.7%

However I don't think the change you made to EstimateFalsePositiveRate is correct. Maybe I'm misunderstanding what you want the function to return so correct me if I'm wrong.

Your current code is:

fpRate = float64(fp) / (float64(rounds) * float64(100))
This means that if we do 100 tests (rounds = 100) of which 20 are false (fp = 20) , we get an fpRate = 20 / (100 * 100) = 0.002 which makes no sense to me. Similar to the input of NewWithEstimates I expect the function to return a percentage in the range of 1 to 0 where 1 equals 100%. At the moment it returns the percentage in the range of 0.01 to 0 where 0.01 equals 100%.

I think the correct code should just be:

fpRate = float64(fp) / float64(rounds)
In the same case as above it would be fpRate = 20 / 100 = 0.2. This way bloom.NewWithEstimates(n, f).EstimateFalsePositiveRate(n) == f should in theory be true (not in practice of course).

Keep in mind that if you change this the TestEstimated* tests will fail again.

**Comment by willf** [comment]
Ok, I now use the best of your method and the best of using the faster FNV hash; on an expanded series of tests, these come in at most 10% over the estimated fp rate. Using FNV is about 6x faster (iirc) than using SHA256. 

Thanks for all your help on this. LMK if you see any more issues.

-- 
Will


On March 30, 2015 at 7:48:00 AM, Will Fitzgerald (will.fitzgerald@gmail.com) wrote:

Argh, you are right of course.

-- 
Will


On March 30, 2015 at 1:43:38 AM, Erik Dubbelboer (notifications@github.com) wrote:

The two base hash works much better than I expected for such a fast hash function. These are the new results (with my fix to EstimateFalsePositiveRate below):

fnv NewWithEstimates(     1000,  0.1%).EstimateFalsePositiveRate(     1000) =  0.2%
fnv NewWithEstimates(    10000,  0.1%).EstimateFalsePositiveRate(    10000) =  0.5%
fnv NewWithEstimates( 10000000,  0.1%).EstimateFalsePositiveRate( 10000000) =  0.5%
fnv NewWithEstimates(100000000,  0.1%).EstimateFalsePositiveRate(100000000) =  0.0%
fnv NewWithEstimates(     1000,  1.0%).EstimateFalsePositiveRate(     1000) =  1.0%
fnv NewWithEstimates(    10000,  1.0%).EstimateFalsePositiveRate(    10000) =  0.5%
fnv NewWithEstimates( 10000000,  1.0%).EstimateFalsePositiveRate( 10000000) =  1.1%
fnv NewWithEstimates(100000000,  1.0%).EstimateFalsePositiveRate(100000000) =  1.1%
fnv NewWithEstimates(     1000,  2.0%).EstimateFalsePositiveRate(     1000) =  0.8%
fnv NewWithEstimates(    10000,  2.0%).EstimateFalsePositiveRate(    10000) =  2.9%
fnv NewWithEstimates( 10000000,  2.0%).EstimateFalsePositiveRate( 10000000) =  0.9%
fnv NewWithEstimates(100000000,  2.0%).EstimateFalsePositiveRate(100000000) =  4.6%
fnv NewWithEstimates(     1000, 10.0%).EstimateFalsePositiveRate(     1000) =  3.9%
fnv NewWithEstimates(    10000, 10.0%).EstimateFalsePositiveRate(    10000) =  6.3%
fnv NewWithEstimates( 10000000, 10.0%).EstimateFalsePositiveRate( 10000000) = 11.4%
fnv NewWithEstimates(100000000, 10.0%).EstimateFalsePositiveRate(100000000) =  5.7%


However I don't think the change you made to EstimateFalsePositiveRate is correct. Maybe I'm misunderstanding what you want the function to return so correct me if I'm wrong.

Your current code is:

fpRate = float64(fp) / (float64(rounds) * float64(100))

This means that if we do 100 tests (rounds = 100) of which 20 are false (fp = 20) , we get an fpRate = 20 / (100 * 100) = 0.002 which makes no sense to me. Similar to the input of NewWithEstimates I expect the function to return a percentage in the range of 1 to 0 where 1 equals 100%. At the moment it returns the percentage in the range of 0.01 to 0 where 0.01 equals 100%.

I think the correct code should just be:

fpRate = float64(fp) / float64(rounds)
In the same case as above it would be fpRate = 20 / 100 = 0.2. This way bloom.NewWithEstimates(n, f).EstimateFalsePositiveRate(n) == f should in theory be true (not in practice of course).

Keep in mind that if you change this the TestEstimated* tests will fail again.
